[package]
name = "ouro"
version = "0.1.5"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive", "env"] }
natpmp = "0.5.0"
eyre = { version = "0.6", features = ["auto-install"] }
tracing = "0.1"
tracing-subscriber = "0.3"
