[package]
name = "vlnr"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
natpmp = "0.5.0"
eyre = "0.6"
